/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ListBusinessRouteImport } from './routes/list-business'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClaimBusinessRouteImport } from './routes/claim-business'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaceSlugRouteImport } from './routes/place.$slug'
import { Route as DashboardMenuRouteImport } from './routes/dashboard.menu'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ListBusinessRoute = ListBusinessRouteImport.update({
  id: '/list-business',
  path: '/list-business',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimBusinessRoute = ClaimBusinessRouteImport.update({
  id: '/claim-business',
  path: '/claim-business',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceSlugRoute = PlaceSlugRouteImport.update({
  id: '/place/$slug',
  path: '/place/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/admin/verifications',
  path: '/admin/verifications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai': typeof AiRoute
  '/claim-business': typeof ClaimBusinessRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/list-business': typeof ListBusinessRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/place/$slug': typeof PlaceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai': typeof AiRoute
  '/claim-business': typeof ClaimBusinessRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/list-business': typeof ListBusinessRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/place/$slug': typeof PlaceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai': typeof AiRoute
  '/claim-business': typeof ClaimBusinessRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/list-business': typeof ListBusinessRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/place/$slug': typeof PlaceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/ai'
    | '/claim-business'
    | '/dashboard'
    | '/discover'
    | '/list-business'
    | '/profile'
    | '/saved'
    | '/admin/verifications'
    | '/dashboard/menu'
    | '/place/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ai'
    | '/claim-business'
    | '/dashboard'
    | '/discover'
    | '/list-business'
    | '/profile'
    | '/saved'
    | '/admin/verifications'
    | '/dashboard/menu'
    | '/place/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/ai'
    | '/claim-business'
    | '/dashboard'
    | '/discover'
    | '/list-business'
    | '/profile'
    | '/saved'
    | '/admin/verifications'
    | '/dashboard/menu'
    | '/place/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AiRoute: typeof AiRoute
  ClaimBusinessRoute: typeof ClaimBusinessRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  ListBusinessRoute: typeof ListBusinessRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  PlaceSlugRoute: typeof PlaceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-business': {
      id: '/list-business'
      path: '/list-business'
      fullPath: '/list-business'
      preLoaderRoute: typeof ListBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-business': {
      id: '/claim-business'
      path: '/claim-business'
      fullPath: '/claim-business'
      preLoaderRoute: typeof ClaimBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$slug': {
      id: '/place/$slug'
      path: '/place/$slug'
      fullPath: '/place/$slug'
      preLoaderRoute: typeof PlaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardMenuRoute: typeof DashboardMenuRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMenuRoute: DashboardMenuRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AiRoute: AiRoute,
  ClaimBusinessRoute: ClaimBusinessRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  ListBusinessRoute: ListBusinessRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  PlaceSlugRoute: PlaceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
